// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerUuid    string                 `protobuf:"bytes,1,opt,name=workerUuid,proto3" json:"workerUuid,omitempty"`
	WorkFinished  string                 `protobuf:"bytes,2,opt,name=workFinished,proto3" json:"workFinished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IFinished) Reset() {
	*x = IFinished{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IFinished) ProtoMessage() {}

func (x *IFinished) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IFinished.ProtoReflect.Descriptor instead.
func (*IFinished) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *IFinished) GetWorkerUuid() string {
	if x != nil {
		return x.WorkerUuid
	}
	return ""
}

func (x *IFinished) GetWorkFinished() string {
	if x != nil {
		return x.WorkFinished
	}
	return ""
}

type ImFree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerUuid    string                 `protobuf:"bytes,1,opt,name=workerUuid,proto3" json:"workerUuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImFree) Reset() {
	*x = ImFree{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImFree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImFree) ProtoMessage() {}

func (x *ImFree) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImFree.ProtoReflect.Descriptor instead.
func (*ImFree) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ImFree) GetWorkerUuid() string {
	if x != nil {
		return x.WorkerUuid
	}
	return ""
}

type AskForWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int32                  `protobuf:"varint,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	ReducerNumber int32                  `protobuf:"varint,2,opt,name=reducerNumber,proto3" json:"reducerNumber,omitempty"`
	WorkType      string                 `protobuf:"bytes,3,opt,name=workType,proto3" json:"workType,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Plugin        string                 `protobuf:"bytes,5,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Response      string                 `protobuf:"bytes,6,opt,name=response,proto3" json:"response,omitempty"`
	MapNumber     int32                  `protobuf:"varint,7,opt,name=mapNumber,proto3" json:"mapNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskForWorkResponse) Reset() {
	*x = AskForWorkResponse{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskForWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskForWorkResponse) ProtoMessage() {}

func (x *AskForWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskForWorkResponse.ProtoReflect.Descriptor instead.
func (*AskForWorkResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *AskForWorkResponse) GetWorkerId() int32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *AskForWorkResponse) GetReducerNumber() int32 {
	if x != nil {
		return x.ReducerNumber
	}
	return 0
}

func (x *AskForWorkResponse) GetWorkType() string {
	if x != nil {
		return x.WorkType
	}
	return ""
}

func (x *AskForWorkResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AskForWorkResponse) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *AskForWorkResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AskForWorkResponse) GetMapNumber() int32 {
	if x != nil {
		return x.MapNumber
	}
	return 0
}

type IFinishedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IFinishedResponse) Reset() {
	*x = IFinishedResponse{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IFinishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IFinishedResponse) ProtoMessage() {}

func (x *IFinishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IFinishedResponse.ProtoReflect.Descriptor instead.
func (*IFinishedResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *IFinishedResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bmessages\"O\n" +
	"\tIFinished\x12\x1e\n" +
	"\n" +
	"workerUuid\x18\x01 \x01(\tR\n" +
	"workerUuid\x12\"\n" +
	"\fworkFinished\x18\x02 \x01(\tR\fworkFinished\"(\n" +
	"\x06ImFree\x12\x1e\n" +
	"\n" +
	"workerUuid\x18\x01 \x01(\tR\n" +
	"workerUuid\"\xe0\x01\n" +
	"\x12AskForWorkResponse\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\x05R\bworkerId\x12$\n" +
	"\rreducerNumber\x18\x02 \x01(\x05R\rreducerNumber\x12\x1a\n" +
	"\bworkType\x18\x03 \x01(\tR\bworkType\x12\x1a\n" +
	"\bfilePath\x18\x04 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06plugin\x18\x05 \x01(\tR\x06plugin\x12\x1a\n" +
	"\bresponse\x18\x06 \x01(\tR\bresponse\x12\x1c\n" +
	"\tmapNumber\x18\a \x01(\x05R\tmapNumber\"/\n" +
	"\x11IFinishedResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2\x8e\x01\n" +
	"\x06Server\x12<\n" +
	"\n" +
	"AskForWork\x12\x10.messages.ImFree\x1a\x1c.messages.AskForWorkResponse\x12F\n" +
	"\x12MarkWorkAsFinished\x12\x13.messages.IFinished\x1a\x1b.messages.IFinishedResponseB\fZ\n" +
	"./messagesb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_messages_proto_goTypes = []any{
	(*IFinished)(nil),          // 0: messages.IFinished
	(*ImFree)(nil),             // 1: messages.ImFree
	(*AskForWorkResponse)(nil), // 2: messages.AskForWorkResponse
	(*IFinishedResponse)(nil),  // 3: messages.IFinishedResponse
}
var file_messages_proto_depIdxs = []int32{
	1, // 0: messages.Server.AskForWork:input_type -> messages.ImFree
	0, // 1: messages.Server.MarkWorkAsFinished:input_type -> messages.IFinished
	2, // 2: messages.Server.AskForWork:output_type -> messages.AskForWorkResponse
	3, // 3: messages.Server.MarkWorkAsFinished:output_type -> messages.IFinishedResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
