// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: protocol/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImFree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImFree) Reset() {
	*x = ImFree{}
	mi := &file_protocol_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImFree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImFree) ProtoMessage() {}

func (x *ImFree) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImFree.ProtoReflect.Descriptor instead.
func (*ImFree) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ImFree) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AskForWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int32                  `protobuf:"varint,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	ReducerNumber int32                  `protobuf:"varint,2,opt,name=reducerNumber,proto3" json:"reducerNumber,omitempty"`
	WorkType      string                 `protobuf:"bytes,3,opt,name=workType,proto3" json:"workType,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Plugin        string                 `protobuf:"bytes,5,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskForWorkResponse) Reset() {
	*x = AskForWorkResponse{}
	mi := &file_protocol_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskForWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskForWorkResponse) ProtoMessage() {}

func (x *AskForWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskForWorkResponse.ProtoReflect.Descriptor instead.
func (*AskForWorkResponse) Descriptor() ([]byte, []int) {
	return file_protocol_messages_proto_rawDescGZIP(), []int{1}
}

func (x *AskForWorkResponse) GetWorkerId() int32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *AskForWorkResponse) GetReducerNumber() int32 {
	if x != nil {
		return x.ReducerNumber
	}
	return 0
}

func (x *AskForWorkResponse) GetWorkType() string {
	if x != nil {
		return x.WorkType
	}
	return ""
}

func (x *AskForWorkResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AskForWorkResponse) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

var File_protocol_messages_proto protoreflect.FileDescriptor

const file_protocol_messages_proto_rawDesc = "" +
	"\n" +
	"\x17protocol/messages.proto\x12\bmessages\"\"\n" +
	"\x06ImFree\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xa6\x01\n" +
	"\x12AskForWorkResponse\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\x05R\bworkerId\x12$\n" +
	"\rreducerNumber\x18\x02 \x01(\x05R\rreducerNumber\x12\x1a\n" +
	"\bworkType\x18\x03 \x01(\tR\bworkType\x12\x1a\n" +
	"\bfilePath\x18\x04 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06plugin\x18\x05 \x01(\tR\x06plugin2F\n" +
	"\x06Server\x12<\n" +
	"\n" +
	"AskForWork\x12\x10.messages.ImFree\x1a\x1c.messages.AskForWorkResponseB\fZ\n" +
	"./messagesb\x06proto3"

var (
	file_protocol_messages_proto_rawDescOnce sync.Once
	file_protocol_messages_proto_rawDescData []byte
)

func file_protocol_messages_proto_rawDescGZIP() []byte {
	file_protocol_messages_proto_rawDescOnce.Do(func() {
		file_protocol_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_messages_proto_rawDesc), len(file_protocol_messages_proto_rawDesc)))
	})
	return file_protocol_messages_proto_rawDescData
}

var file_protocol_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_messages_proto_goTypes = []any{
	(*ImFree)(nil),             // 0: messages.ImFree
	(*AskForWorkResponse)(nil), // 1: messages.AskForWorkResponse
}
var file_protocol_messages_proto_depIdxs = []int32{
	0, // 0: messages.Server.AskForWork:input_type -> messages.ImFree
	1, // 1: messages.Server.AskForWork:output_type -> messages.AskForWorkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_messages_proto_init() }
func file_protocol_messages_proto_init() {
	if File_protocol_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_messages_proto_rawDesc), len(file_protocol_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_messages_proto_goTypes,
		DependencyIndexes: file_protocol_messages_proto_depIdxs,
		MessageInfos:      file_protocol_messages_proto_msgTypes,
	}.Build()
	File_protocol_messages_proto = out.File
	file_protocol_messages_proto_goTypes = nil
	file_protocol_messages_proto_depIdxs = nil
}
